FROM node:22.0.0-alpine

# Create app directory

WORKDIR /app

# Install app dependencies
COPY package.json /app
RUN npm install

# Bundle app source
COPY . /app

RUN npm run build


# Expose port and start application
EXPOSE 3000
CMD ["npm", "start"]
